// @ts-check
/**
 * LUNR static-site build.
 *
 * This site has no framework. To keep analytics IDs out of source while still
 * loading them in the browser, this script:
 *   1. Reads NEXT_PUBLIC_GA_MEASUREMENT_ID / NEXT_PUBLIC_CLARITY_PROJECT_ID from
 *      the environment (set locally via .env, in CI/Vercel via project env vars).
 *   2. Generates `analytics-config.js`, which sets `window.__LUNR_ANALYTICS__`.
 *   3. Copies all static assets into `dist/` (Vercel's output directory).
 *
 * If an ID is absent, the generated config holds `null` and `analytics.js`
 * loads nothing for that tool — no errors, no warnings. No IDs are hardcoded.
 */

import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "dist");

// Load a local .env if present (local dev only). On Vercel/CI there is no .env
// file, so real environment variables are used unchanged.
const ENV_FILE = join(ROOT, ".env");
if (existsSync(ENV_FILE)) {
  process.loadEnvFile(ENV_FILE);
}

/** Static assets copied verbatim into dist/. */
const ASSETS = [
  "index.html",
  "privacy",
  "favicon.svg",
  "LUNR_WHITE.png",
  "analytics.js",
  "robots.txt",
  "sitemap.xml",
];

/**
 * Read an env var, returning null for missing/blank values.
 * @param {string} key
 * @returns {string|null}
 */
function readEnv(key) {
  const v = process.env[key];
  return v && v.trim() ? v.trim() : null;
}

async function main() {
  const gaMeasurementId = readEnv("NEXT_PUBLIC_GA_MEASUREMENT_ID");
  const clarityProjectId = readEnv("NEXT_PUBLIC_CLARITY_PROJECT_ID");

  // Fresh output dir.
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  // Copy assets that exist (skip silently if an optional one is absent).
  for (const asset of ASSETS) {
    const src = join(ROOT, asset);
    if (!existsSync(src)) continue;
    await cp(src, join(OUT, asset), { recursive: true });
  }

  // Generate runtime analytics config from env. Values are JSON-encoded, so a
  // missing ID becomes literal `null`.
  const config = `// AUTO-GENERATED by scripts/build.mjs — do not edit, do not commit.
window.__LUNR_ANALYTICS__ = {
  gaMeasurementId: ${JSON.stringify(gaMeasurementId)},
  clarityProjectId: ${JSON.stringify(clarityProjectId)}
};
`;
  await writeFile(join(OUT, "analytics-config.js"), config, "utf8");

  // Build summary (no warnings — absence is a valid state).
  console.log("[build] dist/ ready");
  console.log(
    `[build] GA4:     ${gaMeasurementId ? "configured" : "not set (GA disabled)"}`,
  );
  console.log(
    `[build] Clarity: ${clarityProjectId ? "configured" : "not set (Clarity disabled)"}`,
  );
}

main().catch((err) => {
  console.error("[build] failed:", err);
  process.exit(1);
});
